### ISSUE TITLE
Submission Pulldown for Selection of Article Type

### ISSUE THREAD

**Issue by katyhuff** [openjournals/jose-old#1]
The authors will need to self-identify which type of article they are submitting (lesson material, or software). We'll need to add that to the submission form so that the bot can pull up the proper review checklist.

**Comment by labarba** [comment]
This is two tasks:

1. adding the drop-down "Submission Type" to the web form (easy task)
2. modifying `whedon` so it knows which review checklist to print on the "Review" issue (not so easy?)

Perhaps task 2 can be made easier by delegating to the editor that commands `whedon` to start the review with choosing the submission type. Something like:

`@whedon start review -type oer magic-word=bananas`
vs
`@whedon start review -type tool magic-word=bananas`

Leaves a margin for human error, but a minor risk I think.

**Comment by labarba** [comment]
@arfon Care to comment on this?

**Comment by arfon** [comment]
> @arfon Care to comment on this?

Sure thing. I don't think Whedon needs to know anything about this as the review checklist is actually described in the JOSS (or JOSE in this case) we application: https://github.com/openjournals/jose/blob/master/app/views/shared/review_body.erb

So we need to adapt the database schema to add a `submission_type` field to the`papers` table. Then we can add some view logic to allow people to pick which type of material they're submitting.

When the editor starts the review (`@whedon start review`) we can just have a case statement in the [`review_body.erb`](https://github.com/openjournals/jose/blob/master/app/views/shared/review_body.erb) to make sure the correct review body is written to the GitHub issue.

Edit: Do you have someone to make these changes?

**Comment by labarba** [comment]
Ah, much better!

**Comment by moorepants** [comment]
> Do you have someone to make these changes?

I think we need an editor that knows Ruby...

**Comment by labarba** [comment]
@arfon : We do _not_ have anyone on hand to make these changes.

**Comment by labarba** [comment]
This was completed as part of the `whedon` upgrade. See:
https://github.com/openjournals/joss/issues/329
