### ISSUE TITLE
Bibtex-badge link giving an error

### ISSUE THREAD

**Issue by labarba** [openjournals/jose-old#19]
When clicking on the JOSS `bibtex` badges from our README of this repo:
https://github.com/barbagroup/pygbe

We get an error. (At least on Safari and Chrome.)

<img width="524" alt="screen shot 2018-07-30 at 5 38 05 pm" src="https://user-images.githubusercontent.com/4800109/43425134-a9c4446e-941f-11e8-821c-d8a84f9082c9.png">

This is the URL the first badge points to:
https://www.doi2bib.org/bib/10.21105%2Fjoss.00043

**Comment by kyleniemeyer** [comment]
Perhaps that was a temporary doi2bib issue? that link works fine for me now.

(I know doi2bib has had some outages in the past)

**Comment by labarba** [comment]
Interesting ... I still get the error. What browser are you on? (typical dumb question)

**Comment by ethanwhite** [comment]
Both badges work for me on Firefox 61.0.1 on Ubuntu 18.04.

**Comment by labarba** [comment]
Yeah, it works on Firefox for @ncclementi, too. Weird.

**Comment by kyleniemeyer** [comment]
It works fine for me on Safari, but Chrome does show the same error you shared.

**Comment by kyleniemeyer** [comment]
(as soon as I tried it again, it did work with Chrome. so I have no idea what's going on)

**Comment by moorepants** [comment]
Worked for me in latest Chrome and Firefox on Ubuntu 18.04 on first try.

**Comment by labarba** [comment]
Gah. I just tried and got the error again (Safari 11.1.1)

![screen shot 2018-08-30 at 8 22 08 am](https://user-images.githubusercontent.com/4800109/44851339-f80e6980-ac2d-11e8-8737-3a1bbf412a9c.png)

**Comment by arfon** [comment]
Closing as stale. We don't use `doi2bib` any longer.
