### ISSUE TITLE
Guidance Document for Authors

### ISSUE THREAD

**Issue by katyhuff** [openjournals/jose-old#2]
Various things need to be included in a guidance document in the about page. 

- [x] Size of a publishable unit (module)
- [x] Meaning of computational curriculum
- [x] Links to guides and research on design of content (e.g. report from MIT on future of education).

**Comment by labarba** [comment]
Link to the MIT Report addressing course modules:
http://web.mit.edu/future-report/TaskForceFinal_July28.pdf
Some quotes:

[p. 13] "…opportunities have been identified by the Task Force: *a) *Exploration of modularity based on learning objectives and measurable outcomes.* […] The way in which students are accessing material points to the need for the modularization of online classes whenever possible. The very notion of a “class” may be outdated. This in many ways mirrors the preferences of students on campus. The unbundling of classes also reflects a larger trend in society… modularity has the added benefit of allowing instructors to develop online material in a more incremental manner"

**Comment by labarba** [comment]
I've added a definition of a "module" ... do you think this is enough? 
https://github.com/openjournals/jose/blob/master/AuthorGuide.md

I wasn't sure whether to tick off the two last items… I only added one link (to the MIT report) and the "meaning of a computational curriculum" seems to be a deeper question!

**Comment by katyhuff** [comment]
I think it looks great! Checking the boxes and closing!
