### ISSUE TITLE
JOSE pre-submission inquiry

### ISSUE THREAD

**Issue by wrightaprilm** [openjournals/jose-old#20]
**Project repository URL:** https://github.com/wrightaprilm/treesiftr

Hello,

I was thinking of submitting an educational resource here. It straddles the two submission types, in that it is an R package to generate and visualize phylogenetic trees (shiny app [here](https://wrightaprilm.shinyapps.io/treesiftr_app/)), and I have some [worksheets](https://github.com/wrightaprilm/treesiftr/tree/master/vignettes) that go with it. A [sample slide deck](https://github.com/wrightaprilm/treesiftr/tree/master/inst/slides) to discuss some of the common phylogenetic tree terms will be in the supplemental material.

I'm wondering if:
- This package is appropriate for JOSE, and if so, which track.
- If I should get the package on CRAN first, or submit here and then put on CRAN.

Obviously, there's still some formatting that would need to be done for JOSE, but I didn't want to do it before I knew if it was appropriate.

Thanks!
April

**Comment by moorepants** [comment]
@wrightaprilm This all seems very appropriate. I recommend making a submission.

**Comment by wrightaprilm** [comment]
Thanks!

I still have some questions - should I submit this as a lesson, or as software? And if software, do I get it on CRAN first, or can I submit it as-is?

**Comment by moorepants** [comment]
I'm going to go out on a limb and say to submit it all together. It can be reviewed as software with accompanying worksheets and supplementary material (slides, etc).

We do not have a requirement that the software be submitted to a package manager, so submission to CRAN is not necessary.

**Comment by wrightaprilm** [comment]
All right then, thanks!
