### ISSUE TITLE
How do we edit the Editor profiles?

### ISSUE THREAD

**Issue by moorepants** [openjournals/jose-old#22]
I can't find any data in this repo that contains these blurbs:
![image](https://user-images.githubusercontent.com/276007/44827972-9d8ff180-abca-11e8-8abc-52699e935029.png)
I'm interested in updating my blurb.

**Comment by kyleniemeyer** [comment]
I'm not sure if all editors have this access, but if you log in on the JOSE website, do you see an "Editors" menu option to the left of "Submit"? If you go there, and scroll to the right, you can see an edit link for each of us.

If you don't have this access (and it may just be @labarba and I), let me know what you want yours to say and I can change it.

**Comment by moorepants** [comment]
I don't see that button when logged in. Here are the changes I want to make:

Name: Jason Moore -> Jason K. Moore

Change description to:

Jason K. Moore is an assistant teaching professor of Mechanical and Aerospace Engineering at the University of California, Davis with teaching and research interests in multibody dynamics, biomechanics, engineering computation, and engineering education. He is very active in the Scientific Python community where he is a core developer of the SymPy and PyDy projects.

Thanks!

**Comment by labarba** [comment]
Done.

**Comment by moorepants** [comment]
Thanks!

**Comment by moorepants** [comment]
Sorry, one more new issue, seems my handles is listed as Robert's:
![selection_262](https://user-images.githubusercontent.com/276007/44881618-23607b00-ac65-11e8-9036-ae0a30abdb6c.png)

**Comment by labarba** [comment]
Fixed.

UI fail (drop-down defaults to top option when entering edit mode).

**Comment by moorepants** [comment]
:) Thanks again.
