### ISSUE TITLE
Link to reviews is currently broken

### ISSUE THREAD

**Issue by houshuang** [openjournals/jose-old#3]

**Comment by kyleniemeyer** [comment]
Hi @houshuang, where is this broken?

**Comment by dohliam** [comment]
I also encountered this issue. The URL for the [JOSE submission tool](http://jose.theoj.org) currently gives a DNS error saying the site can't be reached.

**Comment by houshuang** [comment]
Hi @kyleniemeyer, in the README.md. This link: https://github.com/openjournals/jose-reviews/issues

**Comment by kyleniemeyer** [comment]
Oh, I'm sorry- I thought this was posted on JOSS. 

We do not yet have the submission website up and running—I will make this more clear on the README.

**Comment by kyleniemeyer** [comment]
OK, now this is hopefully more clear.
