### ISSUE TITLE
JOSE pre-submission enquiry

### ISSUE THREAD

**Issue by albi3ro** [openjournals/jose-old#30]
[albi3ro/M4](https://github.com/albi3ro/M4
) 
I've written multiple Julia Jupyter notebooks, most of which fall under computational condensed matter physics.  Some just fall in adjacent areas, like numerics, programming, or physics in general. 

I also enumerate out different skill levels and prerequisites, so some posts are readable for high school students (Projectile Motion), while some would are written for graduate students (Quantum Anomalous Hall Effect and the Chern Number). 

Most are standalone, but some can be read in sequence.  For example, Monte Carlo Calculation of Pi to Markov Chain to Monte Carlo Ferromagnet to Phase Transitions. 

How could I handle a submission given this variety of subjects and levels?  

I see that citations go in the paper.md.  But shouldn't the citations go in the work itself? I don't really understand how to cite a statement of need or a summary.  Or maybe that just doesn't apply to me.

Also, how would it work when I end up writing more?  When I write more, could I end up submitting them?

Hope this would be a good submission.

**Comment by moorepants** [comment]
> How could I handle a submission given this variety of subjects and levels?

A submission should have a common theme in terms of subjects. I don't think the varying levels is an issue.

> I see that citations go in the paper.md. But shouldn't the citations go in the work itself? I don't really understand how to cite a statement of need or a summary. Or maybe that just doesn't apply to me.

Citations should go wherever they need to be. If you reference someone else's work in the paper.md it should be cited. Same goes for your documentation and notebooks. The paper.md should be treated as any other academic paper in this regard.

> Also, how would it work when I end up writing more? When I write more, could I end up submitting them?

You can submit a new version/edition once you have a substantial update.
