### ISSUE TITLE
Update nokogiri gem

### ISSUE THREAD

**Issue by willingc** [openjournals/jose-old#34]
Received a vulnerability warning. It would be good to update the Gemfile.

**Comment by moorepants** [comment]
Seems like two gems need this: https://github.com/openjournals/jose/network/alerts

**Comment by MoacirPetry** [comment]
@willingc Try delete the file "Gemfile.lock" first and after that try the command: `bundle install`, it can help you!

**Comment by arfon** [comment]
Closing as stale (fixed elsewhere)
