### ISSUE TITLE
JOSE pre-submission enquiry

### ISSUE THREAD

**Issue by curiousDTU** [openjournals/jose-old#37]
**Project repository URL:**  https://github.com/curiousDTU/cc-gag

I am teaching a course "Introduction to open source and open standards" to first semester students. I am trying to make students learn git and github. The above repository is the assignment I gave to my students. They are enjoying learning it.  
I want to know can I write a research article on it. As it is very basic and at the same time very useful. Any suggestions or advice would be highly appreciated.

Thanks & Regards,
Shobha Tyagi
Assistant Professor, 
Department of Computer Science & Engineering,
Faculty of Engineering & Technology,
MRIIRS, Faridabad, New Delhi 
GNOME Foundation Member since 2013

**Comment by moorepants** [comment]
We would likely accept materials related to teaching version control but what you show does not have the quality or quantity needed for a JOSE submission. Your materials would need to be more akin to the quality of the Software Carpentry lesson on git: https://swcarpentry.github.io/git-novice/. I'm closing this inquiry. Feel free to reopen a new issue if you develop your materials further.
