### ISSUE TITLE
JOSE needs an ISSN

### ISSUE THREAD

**Issue by kyleniemeyer** [openjournals/jose-old#4]
We can apply here: http://loc.gov/issn/form/

I've begun filling out the form, but will keep this open as a todo...

**Comment by kyleniemeyer** [comment]
From https://www.loc.gov/issn/basics/basics-brochure-serials.html#how

> For electronic serials in a tangible form such as CD-ROM or floppy disk, an actual issue and printouts of title screens should be submitted. For online serials, provide an appropriate URL or e-mail actual issues or mock-ups which will accompany the application form to issn@loc.gov.

**Comment by labarba** [comment]
_The Journal of Open Source Education_
ISSN 2577-3569
