### ISSUE TITLE
Pre-submission enquiry: GAMs in R

### ISSUE THREAD

**Issue by noamross** [openjournals/jose-old#40]
I have a short online course, "Generalized Additive Models in R," that I would like to determine eligibility for submission.  It is an interactive online course that uses external but free (Binder) resources to run student exercises on the back-end.  

The code implementing the interface and interactivity comes from another open-source project, so my contribution is content, all of which is CC-BY.  I believe I would submit it as a learning module.

Course (front end): https://noamross.github.io/gams-in-r-course/
Repository: https://github.com/noamross/gams-in-r-course

**Comment by moorepants** [comment]
Noam, this looks like it is exactly the kind of thing we are looking for. I don't see any reason not to submit.

**Comment by noamross** [comment]
Thanks! I'll get a paper written up.
