### ISSUE TITLE
Review hasn't started since a month

### ISSUE THREAD

**Issue by adeepak7** [openjournals/jose-old#48]
Respected Admin,

Our paper, "1build: Frictionless way of managing project-specific commands" was submitted before a month by the first author @gopinath-langote, but the review hasn't started yet.

This publication matters a lot to me to be done in time.

Therefore I request you to kindly look into this issue.

Thanks

**Comment by adeepak7** [comment]
Respected Admin,

Any updates on this?

**Comment by moorepants** [comment]
I'm not seeing any other issues posted by @gopinath-langote. Closing for now. Please reopen with link to the issue if this is a mistake.
