### ISSUE TITLE
Pre-submission inquiry - A survey and reporting platform

### ISSUE THREAD

**Issue by Alcampopiano** [openjournals/jose-old#53]
Hello all,

I have written a tool for web-based data collection and analysis/reporting. [This submission/project](https://github.com/openjournals/joss-reviews/issues/3036) was kindly rejected from JOSS as it was not considered research software that would fit within their scope.

I am kindly asking if this project fits in JOSE's scope. I am a researcher working in a school board and so this platform is something I designed to help researchers in education primarily; however, web-based surveys and reporting tools are useful for researchers in general.

---

#### Repository
https://github.com/Alcampopiano/OpenQuestion

#### Paper
https://github.com/Alcampopiano/OpenQuestion/blob/master/paper/paper.pdf

#### Docs
https://alcampopiano.github.io/OpenQuestion/

#### Project description:
OpenQuestion is a survey building and reporting platform for web-based data collection. Surveys can be developed using a GUI or programatically by writing Python code. To report on survey results, OpenQuestion provides a Jupyter-like environment for data visualization and document creation.

#### Survey development
![im](https://alcampopiano.github.io/OpenQuestion/img/question_types.gif)

#### Report development
![im](https://alcampopiano.github.io/OpenQuestion/img/report_dev.gif)

#### Automatic chart creation and templating process
![im](https://alcampopiano.github.io/OpenQuestion/img/auto_chart_fig.png)

Thank you for JOSE and JOSS. I sincerely appreciate the work that goes into these journals. 

Any feedback would be much appreciated!

Sincerely,
Allan

**Comment by moorepants** [comment]
Allan,

It looks like it can probably fit. But best if you can read this https://jose.theoj.org/about and the tell use which of the two categories if fits in and why.

**Comment by Alcampopiano** [comment]
Hello and thanks very much for the response. 

I believe OpenQuestion fits into the category of a "Software submission" for the following reason: It is designed to make the educational process of designing surveys, acquiring data, and reporting on results easier.

I would be happy to expand on this reasoning if you would like more justification/clarification.

Take care,
Allan

**Comment by moorepants** [comment]
I think it fits the software submission. Feel free to submit.
