### ISSUE TITLE
Authorea just released a Jupyter "publishing" platform

### ISSUE THREAD

**Issue by moorepants** [openjournals/jose-old#7]
This is interesting and relevant to the efforts here.

https://www.authorea.com/inst/18768

Instead of rolling our own journal software, etc, we could ask if they will brand a journal. Much like PubPub is doing.

**Comment by kyleniemeyer** [comment]
This is definitely interesting, but we plan to accept more than notebooks—and I think GitHub's notebook rendering is pretty good.

(plus, there's been some work behind the scenes on the JOSS framework to make it more easily forkable, and it's almost ready!)

**Comment by moorepants** [comment]
Github's rendering will disable any interactive Javascript in the notebooks, which is one downside (but nbviewer doesn't, I think). Here is an example of Authorea's support for interactive figures: https://www.authorea.com/users/1/articles/27167-the-statistical-likelihood-of-steph-curry-s-ridiculous-shooting-streak. Note that Jupyter notebooks are just one of Authorea's supported document types.

**Comment by moorepants** [comment]
Good to hear that JOSS will be easily forkable.

**Comment by boisgera** [comment]
For interactive notebooks, could binder <https://mybinder.org/> be used?
IMHO it is a great tool and since it is also integrated with GitHub, it seems to be a good fit.
It may also replace the platform used today for "Try Jupyter!" <https://try.jupyter.org/> (see <https://github.com/jupyter/try.jupyter.org/issues/21>) which would probably boost its popularity.

**Comment by moorepants** [comment]
It could super cool to utilize binder for submissions to JOSE, so folks could experience the interactivity.

**Comment by moorepants** [comment]
There are some new tools that can allow Jupyter notebook authors create  web pages that are made "live" by a binder/jupyter backend:

- https://github.com/minrk/thebelab
- https://github.com/SamLau95/nbinteract

Closing this issue, as my original statement is irrelevant since the journal is now live.
